### ISSUE TITLE
Posts not indexed on Google/”Search engines haven’t been notified yet” error

### ISSUE THREAD

**Issue by slis71** [Auctollo/google-sitemap-generator#109]
So 2 posts I published last month are still not showing up in google search (https://smellslikeinfinitesadness.com/episode-47-survival-guides-emily-whitehurst-talks-new-album-deathdreams-slis-podcast/ and https://smellslikeinfinitesadness.com/hackedepicciottos-alexander-hacke-danielle-de-picciotto-talk-new-album-keepsakes/.)
Also my post from last week also hasn't been indexed yet: (https://smellslikeinfinitesadness.com/slowdive-everything-is-alive-review/).

I manually submitted urls via google search console last week but that hasn't helped. To make things even stranger, my most recent post was indexed by google within a day, so I'm not sure why the 3 posts mentioned above still aren't showing up. 

I noticed while checking my XML sitemap generator settings that it says this “Search engines haven’t been notified yet. Write a post to let them know about your sitemap.” No matter how many times I click the update link it still gives that error message.

Could these problems be related, and is there anyway to fix? 

I’m really at a loss on what to do, so any advice would be much appreciated. Thanks!

**Comment by slis71** [comment]
Bump

**Comment by ftownes** [comment]
Hi @slis71: I'm sorry to hear about your trouble. We would have to look at why (soon to be deprecated by Google) notifications aren't working on your server. Given that you've submitted the URLs manually, the issues are definitely not related. If your sitemap is submitted to the Google Search Console or your robots.txt file contains the sitemap hint, there would also be no correlation.

We have planned a tool (in our roadmap) to help demystify why these kinds of issues occur. Unfortunately, yours is not a unique experience, and sitemaps themselves aren't relevant (because they're just a list of URLs).

Please also keep in mind that GitHub is not for support. So I have to close this issue and ask that you move to the WordPress forums instead for further discourse.
